name: Build Windows Executable

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'  # Adjust if needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable with hidden imports
        run: |
          pyinstaller --onefile --noconsole --hidden-import=streamlit app.py
        shell: powershell

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: Image-Video-Colorization-Executable
          path: dist/app.exe
